### ISSUE TITLE
All devices suddenly became completely unverified to a contact

### ISSUE THREAD

**Issue by Trevoke** [wireapp/wire#33] opened 2017-04-19 18:43 UTC
All of my devices suddenly became unverified on my contact's side.

It could be because of an upgrade to the web app.
It could be because of an upgrade to the Android App.
It could be because of an upgrade to the OSX app.
It could be because of a completely separate problem.

Regardless, this is a *significant* problem, as there's no clear reason for ALL OF MY DEVICES to become unverified.

**Comment by Trevoke** [comment] 2017-04-19 18:47
Note - this seems to have happened only on the web app on their side, which means the defect is likely from that new release.

**Comment by teller** [comment] 2017-04-19 19:21
Did you log in on a new device? You'll need to verify that from each existing device to verify the full conversations. Otherwise convo isn't verified as messages get synced to the new, unverified device.

We're looking to simplify the whole verification/identity in the future to overcome these complexities.

**Comment by Trevoke** [comment] 2017-04-19 19:43
I was not using a new device.

According to my contact, the Chrome web app did count as a new device. You're saying that because the Chrome web app counted as a new device, everything was unverified for me because, well, the new device doesn't know me?

So.. Each message is signed from device to device, which means for a full conversation we need to verify all the devices every time.. Which makes device switching expensive..

I see.

**Comment by Trevoke** [comment] 2017-04-20 17:13
You know, even just some text when you notice that an existing user logs in to a new device saying "Hey, you're gonna need to reverify all your contacts' devices" would be helpful to set the correct expectations.

**Comment by david-wire** [comment] 2017-05-11 12:46
Thanks for the feedback, we appreciate the time you took to send us your comments. 
As this is the intended behavior, closing this issue.

**Closed by david-wire** 2017-05-11 12:46 UTC
