### ISSUE TITLE
chat with oneself

### ISSUE THREAD

**Issue by Simplenuity** [wireapp/wire#11] opened 2017-02-26 03:48 UTC
Thanks for this great app!

Beside supporting the requests that have already been posted, I'd like to add the following:

Please allow chatting with oneself. 
Maybe it's already possible and I just couldn't figure it out. Searching for myself by name or user name didn't succeed.

This feature is well implemented in [Telegram Messenger](http://pichost.org/image/16b9) and very useful.
With all the input options Wire is offering it would be an outstanding capture tool!

Thank you for your consideration!

PS: If you prefer me to post this feature request in each app category (iOS, Android, Desktop, ...), please let me know.

**Comment by Namnodorel** [comment] 2017-02-26 10:43
Although you were actually not much behind, I think this is a duplicate of #10. ;)

**Comment by teller** [comment] 2017-02-26 21:42
@Namnodorel Not a dupe. This is about self-chat. #10 is for a topic-based 1:1 chat (today you can only give a topic to chat with minimum 3 members).

**Comment by Namnodorel** [comment] 2017-02-27 14:11
> I'd like to be able to create "named conversations" with just 1 one other person[...] or even just a **named conversation with only myself**

**Comment by david-wire** [comment] 2017-03-17 09:58
@Simplenuity thanks for the note, we do not plan to add this feature at the moment. However, thanks for taking the time to send us your comments, much appreciated.

**Comment by Simplenuity** [comment] 2017-03-17 22:26
Thanks @david-wire for the update, and also for keeping this request open for later reconsideration.
Would be great to have one (main) reason less to keep using Telegram.

Keep up the great work!

**Comment by herrpoerner** [comment] 2017-04-07 19:16
+1 for this feature request. It's one of the features that makes Telegram Messenger sort of a swiss army knife. Very handy to securely send files i.e. from work to home.

**Comment by richpersaud** [comment] 2017-04-07 20:49
+1 for enabling secure file sharing (over Wire) between iOS applications which use the iOS share sheet.

As a workaround, could the Wire client support logins by more than one userid?  Then a 1:1 chat between two users (both logged into the same device) would be possible.

**Comment by maximbaz** [comment] 2017-04-19 14:47
@richpersaud, @alugarius the workaround you can use right now is to create a group chat with two other people, and then deleting them both from the conversation. That will leave you with a chat with yourself only.

**Comment by oscalation** [comment] 2017-06-22 16:53
I to like this feature... I often have something I need to remind myself of real fast and usually send myself a text, message, email.

**Comment by wmengli** [comment] 2017-06-28 10:35
Hi all, 
A very popular topic! This is one of the frequent feature request we have received and within Wire internally too.
What @maximbaz mentioned is a work around and we are looking into options how to drop yourself the reminder messages and contents. No ETA yet but we will announce in our blog or social media once it's available ;-)
We will close this for now and feel free to contact us for other questions.

Thanks all!

Best wishes,
Wire Support Team

**Closed by wmengli** 2017-06-28 10:35 UTC
Labels: feature request

**Comment by maxogden** [comment] 2018-01-17 18:45
@wmengli Any update on this feature? For a workaround I created a bot and just use the bot conversation to talk to myself

**Comment by cardassian-tailor** [comment] 2018-01-19 21:38
has anyone thought of any creative solutions to this? 

If your going to message yourself, we might as well deam it a 'notes' feature, especially if these notes will sync across devices.  But that brings another question, do you want these notes to sync across your devices?

**Comment by maximbaz** [comment] 2018-01-19 21:54
I have been using the chat with myself (via an empty group) precisely for keeping notes, and by now I have already lost all my notes a couple of times "thanks to" the absence of history backup / restore.

That's why I think it's simply too early to dream about a more sophisticated "notes" feature, we can't even rely on the current system as all your notes can be gone in an instant.

**Comment by cardassian-tailor** [comment] 2018-01-19 21:58
@maximbaz I understand and apologize about your difficulty with losing data due to no backup/restore feature -- however you must keep in mind that some have strong concerns about such a feature - as I and others have clearly documented in other threads.

**Comment by chpatton013** [comment] 2019-04-25 16:26
Any update on decisions or timeline here?
