### ISSUE TITLE
F-Droid request

### ISSUE THREAD

**Issue by ghost** [wireapp/wire#403] opened 2023-11-18 22:42 UTC
Hi!

Can you please publish your app on F-Droid officially? Or at least make your own F-Droid repo [like Tor did (link)](https://guardianproject.info/fdroid/repo/)?

F-Droid allows custom keys [(more info)](https://f-droid.org/2023/01/15/towards-a-reproducible-fdroid.html)

**Comment by blacklightpy** [comment] 2023-11-20 17:25
Already here: https://f-droid.org/en/packages/com.wire/

**Comment by tmspzz** [comment] 2023-11-23 17:32
It is in the works to publish v4

**Comment by tmspzz** [comment] 2023-11-23 17:43
closing as duplicate of #387

**Closed by tmspzz** 2023-11-23 17:43 UTC
Labels: Android
