### ISSUE TITLE
Feature Request: Option to hide left-hand menu

### ISSUE THREAD

**Issue by schlichtanders** [wireapp/wire#39] opened 2017-05-04 14:56 UTC
Dear Wire-Team,

it would be great, if one could hide the left part of wire where all the contacts are listed.

Suggestions:
1. make the border between contacts and chat windowpart draggable to decrease/increase the size of the panes respectively (increasing the one, decreasing the other)
1. add a button like a common menu three-bar sign &Xi;  to the *top-left* which can hide/unhide the contacts-pane alltogether. If hidden, there is of course the question where to put &Xi; and I think it is still best to leave it *top-left* and place the search symbol right next to it
1. dragging the border between the panes (from 1.) such far as to hide the contactspane completely, the contactspane could switch to the &Xi; presentation (from 2.)

**Comment by mythsunwind** [comment] 2017-05-04 16:15
Duplicate of https://github.com/wireapp/wire-desktop/issues/298

**Closed by mythsunwind** 2017-05-04 16:15 UTC
